### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by NickSramcik** [NickSramcik/banki-brunch#12]
Our web application could use a favicon, or the little icon that represents the website on browser tabs. 

It's recently come to my attention that different devices prefer different sizes/dimensions for the favicon, so we may need to look into that. 

Some resources on this topic:
https://www.seoptimer.com/blog/what-is-a-favicon/
https://favicon.io
https://www.favicon-generator.org/

**Comment by NickSramcik** [comment]
What do y'all think the favicon should look like?

**Comment by intelagense** [comment]
I would like the issue. I can post some options for the graphic in the project thread on Discord.

**Comment by MITCHYUGAN** [comment]
Yh, a favicon is an important component of a website 👍

**Comment by Jahkamso** [comment]
Favicon would add a more feel to the project.
